    console.log("Start");
    var txt = document.scripts.length;
    console.log("No of scripts loaded " + document.scripts.length );
    console.log("Code 0= " + document.scripts[0].text);
    console.log("Code 1= " + document.scripts[1].text);
    console.log("Code 2= " + document.scripts[2].text);
    console.log("Code 3= " + document.scripts[3].text);
    console.log("Reading document.domain");
    console.log(document.domain);
    console.log('end');
